permalink: /:year/:month/:title.html
highlights: pygments
highlight: true
markdown: kramdown
highlighter: rouge

safe: true
#paginate: 8
#paginate_path: "page:num"

# presonal config
url: https://zacharyyang.github.io
domain: https://zacharyyang.github.io
title: iLinux
author: Zachary
email: zacharyang@163.com
github: zachary

config:
  js_dir:
  img_dir:
  css_dir:
